### PR TITLE
Fix null pointer crashes when running a plugin as a standalone window

### LINKED ISSUE #687: Critical: Null pointer dereference crashes in gz-gui plugins during initialization
## Environment
* OS Version:  Ubuntu24.04
* Source or binary build?
  source,gz-gui9

## Description
* Expected behavior:  lanuch gui correctly
* Actual behavior: crash

## Steps to reproduce

Actually, I find 13 plugins that have null pointer problem when I use `gz gui -s` to lanuch ,they are 
```
CameraFps
CameraTracking
CameraTrackingConfig
GridConfig
InteractiveViewControl
KeyPublisher
MarkerManager
MinimalScene
PointCloud
Screenshot
TapeMeasure
Teleop
TransportSceneManager
``` 
1. gz gui -s [anyone in list above]
2. crash
## Output
only dispaly one of them behind,their stack trace are almost similar. [crash_logs.zip](https://github.com/user-attachments/files/20809553/crash_logs.zip)

```
Stack trace (most recent call last):
#24   Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#23   Object "gz gui -s Teleop", at 0x56c54e57c1d4, in _start
#22   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7b7bc0a2a28a, in __libc_start_main
#21   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7b7bc0a2a1c9, in 
#20   Object "gz gui -s Teleop", at 0x56c54e57c186, in 
#19   Object "/lib/x86_64-linux-gnu/libruby-3.2.so.3.2", at 0x7b7bc0eb9192, in ruby_run_node
#18   Object "/lib/x86_64-linux-gnu/libruby-3.2.so.3.2", at 0x7b7bc0eb4e5b, in 
#17   Object "/lib/x86_64-linux-gnu/libruby-3.2.so.3.2", at 0x7b7bc1057b39, in rb_vm_exec
#16   Object "/lib/x86_64-linux-gnu/libruby-3.2.so.3.2", at 0x7b7bc10545db, in 
#15   Object "/lib/x86_64-linux-gnu/libruby-3.2.so.3.2", at 0x7b7bc10500fe, in 
#14   Object "/lib/x86_64-linux-gnu/libruby-3.2.so.3.2", at 0x7b7bc104d8ef, in 
#13   Object "/usr/lib/x86_64-linux-gnu/ruby/3.2.0/fiddle.so", at 0x7b7bbf0f7b13, in 
#12   Object "/lib/x86_64-linux-gnu/libruby-3.2.so.3.2", at 0x7b7bc10163bb, in rb_nogvl
#11   Object "/usr/lib/x86_64-linux-gnu/ruby/3.2.0/fiddle.so", at 0x7b7bbf0f743b, in 
#10   Object "/lib/x86_64-linux-gnu/libffi.so.8", at 0x7b7bc084a0bd, in ffi_call
#9    Object "/lib/x86_64-linux-gnu/libffi.so.8", at 0x7b7bc08473ee, in 
#8    Object "/lib/x86_64-linux-gnu/libffi.so.8", at 0x7b7bc084ab15, in 
#7    Object "/home/momo/w_s/install/lib/libgz-gui9.so.9.0.1", at 0x7b7bba9d6845, in cmdStandalone
#6    Object "/home/momo/w_s/install/lib/libgz-gui9.so.9.0.1", at 0x7b7bba996007, in gz::gui::Application::LoadPlugin(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tinyxml2::XMLElement const*)
#5    Object "/home/momo/w_s/install/lib/libgz-gui9.so.9.0.1", at 0x7b7bbaa8b227, in gz::gui::Plugin::Load(tinyxml2::XMLElement const*)
#4    Object "/home/momo/w_s/install/lib/gz-gui-9/plugins/libTeleop.so", at 0x7b7bb01c35be, in gz::gui::plugins::Teleop::LoadConfig(tinyxml2::XMLElement const*)
#3    Object "/home/momo/w_s/install/lib/libgz-gui9.so.9.0.1", at 0x7b7bba9e451d, in gz::gui::MainWindow::QuickWindow() const
#2    Object "/home/momo/w_s/install/lib/libgz-gui9.so.9.0.1", at 0x7b7bba9eab3b, in std::unique_ptr<gz::gui::MainWindow::Implementation, void (*)(gz::gui::MainWindow::Implementation*)>::operator->() const
#1    Object "/home/momo/w_s/install/lib/libgz-gui9.so.9.0.1", at 0x7b7bba9ef107, in std::unique_ptr<gz::gui::MainWindow::Implementation, void (*)(gz::gui::MainWindow::Implementation*)>::get() const
#0    Object "/home/momo/w_s/install/lib/libgz-gui9.so.9.0.1", at 0x7b7bba9f3320, in std::__uniq_ptr_impl<gz::gui::MainWindow::Implementation, void (*)(gz::gui::MainWindow::Implementation*)>::_M_ptr() const
```

### PR DESCRIPTION
**Pull request by XINJIANGMO**
# 🦟 Bug fix

Fixes #687 

## Summary

The fix replaces unsafe direct pointer dereferences with null pointer checks to prevent potential crashes.
before fix : use `gz gui -s` plus any plugin noted in #687 , gazebo crashes
after fix: `gz gui -s` plus any plugin noted in #687 , gazebo workes correctly as expected
## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))

### CODE REVIEW

File: src/plugins/point_cloud/PointCloud.cc [hunk 1]
```diff
@@ -139,8 +139,11 @@ void PointCloud::LoadConfig(const tinyxml2::XMLElement *_pluginElem)
 
   }
 
-  gz::gui::App()->findChild<
-    gz::gui::MainWindow *>()->installEventFilter(this);
+  if (auto app = gz::gui::App()) {
+    if (auto mainWindow = app->findChild<gz::gui::MainWindow *>()) {
+          mainWindow->installEventFilter(this);
+    }
```
Comment (ahcorde) [inline src/plugins/point_cloud/PointCloud.cc:145]:
```suggestion
    if (auto mainWindow = app->findChild<gz::gui::MainWindow *>()) {
      mainWindow->installEventFilter(this);
    }
```
